/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export type Decimal = ColumnType<string, number | string>;



export interface Course {
  CourseID?: number;
  CourseName: string;
}

export interface Exam {
  ExamDate: Date;
  ExamID?: number;
  Grade?: Decimal;
  UserID?: string;
}

export interface ExamQuestion {
  AnswerOptions: string;
  CorrectAnswer: string;
  IsActive?: number | null;
  QuestionID?: number;
  QuestionPicURL: string;
  TopicID: number;
}

export interface ExamResult {
  ExamID: number;
  Grade?: Decimal | null;
  IsCorrect?: number;
  Position?: number;
  QuestionID: number;
  SelectedAnswer?: string | null;
}

export interface PracticeExercise {
  AnswerOptions: string;
  ContentType?: string;
  ContentValue?: string;
  CorrectAnswer: string;
  Difficulty?: "easy" | "exam" | "medium" | null;
  ExerciseID?: number;
  TopicID: number;
}

export interface PracticeVideo {
  Difficulty: "easy" | "exam" | "intro" | "medium";
  TopicID: number;
  VideoID?: number;
  VideoTopic: string;
  VideoUrl: string;
}

export interface SiteVisit {
  UserID?: string;
  visit_count?: number;
  VisitedAt?: Date;
}

export interface Topic {
  CourseID: number;
  TopicDescription?: string | null;
  TopicID?: number;
  TopicName: string;
}

export interface Users {
  CourseID: number;
  Email: string;
  expired_date?: Date | null;
  Name: string;
  Password: string;
  Role: "Admin" | "Examinee" | "Teacher";
  UserID?: string;
}

export interface DB {
  course: Course;
  exam: Exam;
  exam_question: ExamQuestion;
  exam_result: ExamResult;
  practice_exercise: PracticeExercise;
  practice_video: PracticeVideo;
  site_visit: SiteVisit;
  topic: Topic;
  users: Users;
}
