// בקובץ זה נמצא רכיב הטופס ליצירה ועריכה של נושאים במערכת
// הקובץ מספק טופס פשוט עם שדה שם נושא בלבד
// הוא תומך במצבי הוספה ועריכה ומציג כפתורי שמירה וביטול
// מזהה הנושא והקורס מטופלים אוטומטית על ידי השרת

// Frontend/src/pages/manager/manageContent/TopicForm.jsx
import React, { useState } from "react";
import styles from "../adminPages.module.css";

/**
 * @component TopicForm
 * @description A form for creating or editing a topic. It includes only the topic name field.
 * The TopicID is auto-generated by the database, and CourseID is inferred from the user's JWT token.
 * @param {object} props - The component props.
 * @param {object} props.initialValues - The initial values for the form fields (TopicName).
 * @param {Function} props.onSubmit - The function to call when the form is submitted.
 * @param {Function} props.onClose - The function to call when the cancel button is clicked.
 * @param {string} props.mode - The mode of the form, either 'add' or 'edit'.
 * @returns {JSX.Element} The rendered topic form.
 */
export default function TopicForm({ initialValues, onSubmit, onClose, mode }) {
  const [topicName, setTopicName] = useState(initialValues.TopicName || "");

  return (
    <form
      className={styles.form}
      onSubmit={(e) => {
        e.preventDefault();
        if (!topicName.trim()) {
          alert("יש להזין שם נושא");
          return;
        }
        onSubmit({
          TopicName: topicName,
        });
      }}
    >
      <div className={styles.inputContainer}>
        <label className={styles.label}>שם נושא</label>
        <input
          className={styles.input}
          type="text"
          value={topicName}
          onChange={(e) => setTopicName(e.target.value)}
          placeholder="הזן שם נושא"
          required
        />
      </div>
      <div style={{ display: 'flex', gap: '12px', justifyContent: 'center', width: '100%' }}>
        <button className={styles.submitButton} type="submit" style={{ flex: 1 }}>
          {mode === "edit" ? "שמור" : "הוסף"}
        </button>
        <button
          className={styles.smallButton}
          type="button"
          onClick={onClose}
          style={{ flex: 1, padding: '0.7rem 1.2rem' }}
        >
          ביטול
        </button>
      </div>
    </form>
  );
}
